In [ ]:
!pip install python-docx

Collecting python-docx
  Downloading python_docx-1.1.2-py3-none-any.whl (244 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.3/244.3 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from python-docx) (4.9.4)
Requirement already satisfied: typing-extensions>=4.9.0 in /usr/local/lib/python3.10/dist-packages (from python-docx) (4.11.0)
Installing collected packages: python-docx
Successfully installed python-docx-1.1.2

In [ ]:
!pip install -q tiktoken==0.5.2 langchain_community==0.0.11 langchain==0.1.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 10.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 42.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 798.0/798.0 kB 10.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.9/302.9 kB 17.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 kB 3.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 kB 3.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.9/302.9 kB 18.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.8/302.8 kB 21.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 303.0/303.0 kB 23.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.9/302.9 kB 20.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.2/302.2 kB 15.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 299.3/299.3 kB 20.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 291.3/291.3 kB 21.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 290.2/290.2 kB 18.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 289.1/289.1 kB 14.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.5/287.5 kB 17.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.4/278.4 kB 16.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 276.8/276.8 kB 20.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 276.6/276.6 kB 18.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 279.2/279.2 kB 22.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 274.6/274.6 kB 26.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 273.9/273.9 kB 25.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 273.0/273.0 kB 26.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 271.6/271.6 kB 23.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.1/269.1 kB 25.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 260.9/260.9 kB 21.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 258.8/258.8 kB 24.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 256.9/256.9 kB 23.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 252.6/252.6 kB 22.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 252.4/252.4 kB 23.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.8/250.8 kB 24.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 246.4/246.4 kB 23.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.1/242.1 kB 24.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.3/241.3 kB 22.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 241.2/241.2 kB 21.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.4/55.4 kB 5.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 6.1 MB/s eta 0:00:00

In [ ]:
from google.colab import userdata
import numpy as np
import os
import io
import tempfile
import tiktoken
from docx import Document
from scipy.spatial.distance import cdist
import json
import re
import requests
from google.colab import userdata
from langchain.text_splitter import RecursiveCharacterTextSplitter, MarkdownHeaderTextSplitter, CharacterTextSplitter
from langchain.docstore.document import Document as Doc
import pickle

In [ ]:
ID_FOLDER = userdata.get('ID_FOLDER')
OAuth_token = userdata.get('OAuth_token')

In [ ]:
# URL для получения токена
URL = "https://iam.api.cloud.yandex.net/iam/v1/tokens"

# Получение IAM-токена (с помощью request)
import requests

headers = {"Content-Type": "application/json"}

data = {
    "yandexPassportOauthToken": OAuth_token
}

response = requests.post(URL, headers=headers, json=data)

IAM_TOKEN = response.json()["iamToken"]
expiresAt = response.json()["expiresAt"]

print(f'Ваш токен действителен до: {expiresAt}')

Ваш токен действителен до: 2024-05-15T18:41:07.495856603Z

In [ ]:
#Готовая база для Markdown: v3.0: https://drive.google.com/file/d/1e4U1IoxumnkW0ttZ-n3CDnDMKX4Qvco-/view?usp=sharing
id_doc_markdown = '1e4U1IoxumnkW0ttZ-n3CDnDMKX4Qvco-'

In [ ]:
# функция для загрузки документа по doc_id из гугл драйв в текстовом формате
def load_doc_id_text(file_id):
    # Download the document as plain text
    response = requests.get(f'https://drive.google.com/uc?export=download&id={file_id}')
    response.raise_for_status()
    text = response.text

    return text

In [ ]:
data_from_markdown = load_doc_id_text(id_doc_markdown)

In [ ]:
def num_tokens_from_string(string: str, encoding_name: str) -> int:
      """Возвращает количество токенов в строке"""
      encoding = tiktoken.get_encoding(encoding_name)
      num_tokens = len(encoding.encode(string))
      return num_tokens

def split_text(text, max_count):
    headers_to_split_on = [
        ("#", "Header 1"),
        ("##", "Header 2"),
        ("###", "Header 3"),
        ("####", "Header 4"),
        ("#####", "Header 5"),
    ]

    markdown_splitter = MarkdownHeaderTextSplitter(headers_to_split_on=headers_to_split_on)
    fragments = markdown_splitter.split_text(text)

    # Подсчет токенов для каждого фрагмента
    fragment_token_counts = [num_tokens_from_string(fragment.page_content, "cl100k_base") for fragment in fragments]

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=max_count,
        chunk_overlap=0,
        length_function=lambda x: num_tokens_from_string(x, "cl100k_base")
    )

    source_chunks = [
        Doc(page_content=chunk, metadata=fragment.metadata)
        for fragment in fragments
        for chunk in splitter.split_text(fragment.page_content)
    ]

    # Подсчет токенов для каждого source_chunk
    source_chunk_token_counts = [num_tokens_from_string(chunk.page_content, "cl100k_base") for chunk in source_chunks]

    return source_chunks, fragments

In [ ]:
source_chunks, fragments = split_text(data_from_markdown, 1000)
print("Общее количество чанков: ",len(source_chunks))
print("Первый чанк ", source_chunks[0])
print("Metadata Первого чанка", source_chunks[0].metadata)
print("Крайний чанк ", source_chunks[len(source_chunks)-1])
print("Metadata крайнего чанка", source_chunks[len(source_chunks)-1].metadata)

Общее количество чанков:  1266
Первый чанк  page_content='Документ предоставлен КонсультантПлюс'
Metadata Первого чанка {}
Крайний чанк  page_content='5. На оборотной стороне свидетельств о поверке при оформлении их на бумажном носителе или в свидетельствах о поверке, оформляемых в виде электронного документа, по заявлению владельцев средств измерений или лиц, представивших средства измерений на поверку, или по согласованию с ними может указываться дополнительная информация, относящаяся к средствам измерений, месту их установки, особенностям поверки, включая сведения о пломбах, предотвращающих доступ к местам настройки (регулировки) средств измерений, принадлежности средств измерений (сведения о владельцах средств измерений), а также информация о прилагаемых к свидетельству о поверке документах (при невозможности размещения информации на оборотной стороне свидетельства о поверке при оформлении его на бумажном носителе).' metadata={'Header 1': 'ТРЕБОВАНИЯ К СОДЕРЖАНИЮ СВИДЕТЕЛЬСТВА О ПОВЕРКЕ', 'Header 2': 'пункт 5.'}
Metadata крайнего чанка {'Header 1': 'ТРЕБОВАНИЯ К СОДЕРЖАНИЮ СВИДЕТЕЛЬСТВА О ПОВЕРКЕ', 'Header 2': 'пункт 5.'}

In [ ]:
separator = ","
result = separator.join([f"{k}. {v}" for k, v in source_chunks[len(source_chunks)-1].metadata.items()])
print (result)

Header 1. ТРЕБОВАНИЯ К СОДЕРЖАНИЮ СВИДЕТЕЛЬСТВА О ПОВЕРКЕ,Header 2. пункт 5.

In [ ]:
#Переведем все метадата чанков в вид, который необходим для Embedding YandexGPT
doc_metadata = []
separator = ","
for i in range(len(source_chunks)):
    result = separator.join([f"{k}. {v}" for k, v in source_chunks[i].metadata.items()])
    text = f'"""{result}""",'
    doc_metadata.append(text)

In [ ]:
doc_metadata

In [ ]:
print(type(source_chunks[len(source_chunks)-1].metadata))
txt_str = f'{json.dumps(source_chunks[len(source_chunks)-1].metadata, ensure_ascii=False)}'
print (type(txt_str), txt_str)

<class 'dict'>
<class 'str'> {"Header 1": "ТРЕБОВАНИЯ К СОДЕРЖАНИЮ СВИДЕТЕЛЬСТВА О ПОВЕРКЕ"}

In [ ]:
#Переведем все чанки в вид, который необходим для Embedding YandexGPT
doc_texts = []
for i in range(len(source_chunks)):
    text = f'"""{source_chunks[i].page_content}""",'
    doc_texts.append(text)

In [ ]:
#Сохраним подготовленную базу в файл
with open('doc_texts_03.pkl', 'wb') as file:
    pickle.dump(doc_texts, file)

In [ ]:
#Выгрузим подготовленную базу для embedding из файла
with open ('doc_texts_03.pkl', 'rb') as file :
    doc_texts = pickle.load(file)

In [ ]:
print (type(doc_texts), len(doc_texts))

<class 'list'> 1266

In [ ]:
#Embedding YandexGPT
doc_uri = f"emb://{ID_FOLDER}/text-search-doc/latest"
query_uri = f"emb://{ID_FOLDER}/text-search-query/latest"

embed_url = "https://llm.api.cloud.yandex.net:443/foundationModels/v1/textEmbedding"
headers = {"Content-Type": "application/json", "Authorization": f"Bearer {IAM_TOKEN}", "x-folder-id": f"{ID_FOLDER}"}



def get_embedding(text: str, text_type: str = "doc") -> np.array:
    query_data = {
        "modelUri": doc_uri if text_type == "doc" else query_uri,
        "text": text,
    }

    return np.array(
        requests.post(embed_url, json=query_data, headers=headers).json()["embedding"]
    )

In [ ]:
#Embedding базы знаний
docs_embedding = [get_embedding(doc_text) for doc_text in doc_texts]
#docs_embedding

In [ ]:
#Сохраним Embedding базы знаний в файл
np.save('docs_embedding_03.npy', docs_embedding)

In [ ]:
#загрузка массива embeddings
docs_embedding = np.load('docs_embedding_03.npy')

In [ ]:
print(type(docs_embedding), len(docs_embedding))

<class 'numpy.ndarray'> 1266

In [ ]:
# most similar doc text
#print(np.argmax(sim), doc_texts[np.argmax(sim)])

In [ ]:
#функция вывода k релевантных чанков по косинусному расстоянию
def get_k_max_indices(arr, k):
    indices = np.argpartition(arr, -k)[-k:]
    return indices

In [ ]:
system = "Ты юридический консультант по метрологическому обеспечению, ответь подробно на вопрос клиента на основании отрывков представленных ответов. При ответе ссылайся на статьи, главы и пункты нормативной документации. Не придумывай ничего от себя. Не отвечай на вопросы, не касающиеся метрологического обеспечения."

In [ ]:
#Функция обращения к модели YandexGPT Pro
def get_gpt_ya_response (ID_FOLDER, question):
    prompt = {
        "modelUri": f"gpt://{ID_FOLDER}/yandexgpt", # yandexgpt - модель YandexGPT pro
        "completionOptions": {
            "stream": False,
            "temperature": 0.0,
            "maxTokens": 2000
        },
            "messages": [
                {
                "role": "system",
                "text": f"{system}"
                },
                {
                "role": "user",
                "text": f"{question}"
                }
            ]
    }


    url = "https://llm.api.cloud.yandex.net/foundationModels/v1/completion"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {IAM_TOKEN}"
    }

    response = requests.post(url, headers=headers, json=prompt)
    json_data = json.loads(response.text)
    answer = json_data['result']['alternatives'][0]['message']['text']
    return answer

In [ ]:
#Функция получения релевантных чанков и метаданных и подготовка вопроса в LLM:
def chunks_metadata_question(query_text):
    #получем embedding вопроса
    query_embedding = get_embedding(query_text, text_type="query")
    # Вычисляем косинусное расстояние
    dist = cdist(query_embedding[None, :], docs_embedding, metric="cosine")
    # Вычисляем косинусное сходство
    sim = 1 - dist
    k = 3 #количество релевантных чанков
    indices = get_k_max_indices(sim, k)
    #находим индексы k релевантных чанков
    ind_k = indices[0][-k:]
    #выведем косинусное расстояние для найденных чанков
    for ind in ind_k: print(sim[0, ind])
    #Подтягиваем релевантные чанки из базы данных
    docs = []
    doc_meta = []
    for ind in ind_k:
        docs.append(doc_texts[ind])
        doc_meta.append(doc_metadata[ind])
    message_content = re.sub(r'\n{2}', ' ', '\n '.join([f'\nОтрывок документа №{i+1}\n=====================' + doc_meta[i] + ', ' + doc + '\n' for i, doc in enumerate(docs)]))
    print (message_content)
    question = f"Вопрос клиента: \n{query_text}\nОтветь на вопрос клиента. Не упоминай документ с информацией для ответа клиенту в ответе. Документ с информацией для ответа клиенту: {message_content}"
    return question

In [ ]:
#Доработка обращения к YandexGPT
query_text = 'Какой нормативный правовой акт устанавливает перечень измерений, реализуемых в сфере государственного регулирования обеспечения единства измерений при выполнении поручений суда, органов прокуратуры, государственных органов исполнительной власти, в том числе обязательные метрологические требования к ним.'
gpt_answer = get_gpt_ya_response(ID_FOLDER, chunks_metadata_question(query_text))
print ("Ответ YaGPT:\n", "=================\n", gpt_answer)

0.5032664369360146
0.5060329891453981
0.518690651889786

Отрывок документа №1
====================="""Header 1. ПРАВИТЕЛЬСТВО РОССИЙСКОЙ ФЕДЕРАЦИИ ПОСТАНОВЛЕНИЕ от 20 апреля 2010 г. N 250 О ПЕРЕЧНЕ СРЕДСТВ ИЗМЕРЕНИЙ, ПОВЕРКА КОТОРЫХ ОСУЩЕСТВЛЯЕТСЯ ТОЛЬКО АККРЕДИТОВАННЫМИ В УСТАНОВЛЕННОМ ПОРЯДКЕ В ОБЛАСТИ ОБЕСПЕЧЕНИЯ ЕДИНСТВА ИЗМЕРЕНИЙ ГОСУДАРСТВЕННЫМИ РЕГИОНАЛЬНЫМИ ЦЕНТРАМИ МЕТРОЛОГИИ""",, """В соответствии со статьей 13 Федерального закона "Об обеспечении единства измерений" Правительство Российской Федерации постановляет:""",
Отрывок документа №2
====================="""Header 1. ПРАВИТЕЛЬСТВО РОССИЙСКОЙ ФЕДЕРАЦИИ ПОСТАНОВЛЕНИЕ от 16 ноября 2020 г. N 1847 ОБ УТВЕРЖДЕНИИ ПЕРЕЧНЯ ИЗМЕРЕНИЙ, ОТНОСЯЩИХСЯ К СФЕРЕ ГОСУДАРСТВЕННОГО РЕГУЛИРОВАНИЯ ОБЕСПЕЧЕНИЯ ЕДИНСТВА ИЗМЕРЕНИЙ""",, """В соответствии с частью 5 статьи 5 Федерального закона "Об обеспечении единства измерений" Правительство Российской Федерации постановляет:""",
Отрывок документа №3
====================="""Header 1. Статья 22. Метрологические службы,Header 2. Статья 27. Заключительные положения,Header 3. пункт 3.""",, """3. Нормативные правовые акты Правительства Российской Федерации, а также метрологические правила и нормы, принятые во исполнение Закона Российской Федерации от 27 апреля 1993 года N 4871-1 "Об обеспечении единства измерений", действуют в части, не противоречащей настоящему Федеральному закону, со дня вступления в силу настоящего Федерального закона и до дня вступления в силу нормативных правовых актов Российской Федерации, предусмотренных настоящим Федеральным законом.""",

Ответ YaGPT:
 =================
 Перечень измерений, реализуемых в сфере государственного регулирования обеспечения единства измерений при выполнении поручений суда, органов прокуратуры, государственных органов исполнительной власти, а также обязательные метрологические требования к ним устанавливаются **Постановлением Правительства Российской Федерации от 16 ноября 2020 г. № 1847**.

Этот документ был принят в соответствии с частью 5 статьи 5 Федерального закона «Об обеспечении единства измерений».

In [ ]:
#Вопрос пользователя
query_text = 'О чем Приказ №2906?'
gpt_answer = get_gpt_ya_response(ID_FOLDER, chunks_metadata_question(query_text))
print ("Ответ YaGPT:\n", "=================\n", gpt_answer)

0.45445522199798427
0.45661510924272264
0.465036980162414

Отрывок документа №1
====================="""Header 1. МИНИСТЕРСТВО ПРОМЫШЛЕННОСТИ И ТОРГОВЛИ РОССИЙСКОЙ ФЕДЕРАЦИИ ПРИКАЗ от 28 августа 2020 г. N 2907 ОБ УТВЕРЖДЕНИИ ПОРЯДКА УСТАНОВЛЕНИЯ И ИЗМЕНЕНИЯ ИНТЕРВАЛА МЕЖДУ ПОВЕРКАМИ СРЕДСТВ ИЗМЕРЕНИЙ, ПОРЯДКА УСТАНОВЛЕНИЯ, ОТМЕНЫ МЕТОДИК ПОВЕРКИ И ВНЕСЕНИЯ ИЗМЕНЕНИЙ В НИХ, ТРЕБОВАНИЙ К МЕТОДИКАМ ПОВЕРКИ СРЕДСТВ ИЗМЕРЕНИЙ,Header 2. пункт 2.""",, """2. Контроль за исполнением настоящего приказа возложить на заместителя Министра промышленности и торговли Российской Федерации А.С. Беспрозванных.
Врио Министра
Г.М.КАДЫРОВА
Приложение N 1
к приказу Минпромторга России
от 28 августа 2020 г. N 2907""",
Отрывок документа №2
====================="""Header 1. МИНИСТЕРСТВО ПРОМЫШЛЕННОСТИ И ТОРГОВЛИ РОССИЙСКОЙ ФЕДЕРАЦИИ ПРИКАЗ от 28 августа 2020 г. N 2906 ОБ УТВЕРЖДЕНИИ ПОРЯДКА СОЗДАНИЯ И ВЕДЕНИЯ ФЕДЕРАЛЬНОГО ИНФОРМАЦИОННОГО ФОНДА ПО ОБЕСПЕЧЕНИЮ ЕДИНСТВА ИЗМЕРЕНИЙ, ПЕРЕДАЧИ СВЕДЕНИЙ В НЕГО И ВНЕСЕНИЯ ИЗМЕНЕНИЙ В ДАННЫЕ СВЕДЕНИЯ, ПРЕДОСТАВЛЕНИЯ СОДЕРЖАЩИХСЯ В НЕМ ДОКУМЕНТОВ И СВЕДЕНИЙ,Header 2. пункт 3.""",, """3. Контроль за исполнением настоящего приказа возложить на заместителя Министра промышленности и торговли Российской Федерации А.С. Беспрозванных.
Врио Министра
Г.М.КАДЫРОВА
Утвержден
приказом Минпромторга России
от 28 августа 2020 г. N 2906""",
Отрывок документа №3
====================="""Header 1. МИНИСТЕРСТВО ПРОМЫШЛЕННОСТИ И ТОРГОВЛИ РОССИЙСКОЙ ФЕДЕРАЦИИ ПРИКАЗ от 15 декабря 2015 г. N 4091 ОБ УТВЕРЖДЕНИИ ПОРЯДКА АТТЕСТАЦИИ ПЕРВИЧНЫХ РЕФЕРЕНТНЫХ МЕТОДИК (МЕТОДОВ) ИЗМЕРЕНИЙ, РЕФЕРЕНТНЫХ МЕТОДИК (МЕТОДОВ) ИЗМЕРЕНИЙ И МЕТОДИК (МЕТОДОВ) ИЗМЕРЕНИЙ И ИХ ПРИМЕНЕНИЯ,Header 2. пункт 2.""",, """2. Контроль за исполнением настоящего приказа возложить на первого заместителя Министра Никитина Г.С.
Министр
Д.В.МАНТУРОВ
Утвержден
приказом Минпромторга России
от 15 декабря 2015 г. N 4091""",

Ответ YaGPT:
 =================
 Приказ №2906 утверждает порядок создания и ведения Федерального информационного фонда по обеспечению единства измерений, передачи сведений в него и внесения изменений в данные сведения, предоставления содержащихся в нём документов и сведений.

In [ ]:
#Вопрос пользователя
query_text = 'ЦСМ отказал в поверке газового счетчика по причине отсутствия у меня действующего договора на техническое обслуживание внутридомового газового оборудования со специализированной организацией. Насколько правомерны действия ЦСМ.'
gpt_answer = get_gpt_ya_response(ID_FOLDER, chunks_metadata_question(query_text))
print ("Ответ YaGPT:\n", "=================\n", gpt_answer)

0.3889358579640556
0.40138068584939823
0.3945804720500916

Отрывок документа №1
====================="""Header 1. ТРЕБОВАНИЯ К СОДЕРЖАНИЮ СВИДЕТЕЛЬСТВА О ПОВЕРКЕ,Header 2. пункт 2.""",, """2. Настоящие требования применяются при оформлении результатов поверки средств измерений.""",
Отрывок документа №2
====================="""Header 1. МИНИСТЕРСТВО ПРОМЫШЛЕННОСТИ И ТОРГОВЛИ РОССИЙСКОЙ ФЕДЕРАЦИИ ПРИКАЗ от 25 июня 2013 г. N 971 ОБ УТВЕРЖДЕНИИ АДМИНИСТРАТИВНОГО РЕГЛАМЕНТА ПО ПРЕДОСТАВЛЕНИЮ ФЕДЕРАЛЬНЫМ АГЕНТСТВОМ ПО ТЕХНИЧЕСКОМУ РЕГУЛИРОВАНИЮ И МЕТРОЛОГИИ ГОСУДАРСТВЕННОЙ УСЛУГИ ПО ОТНЕСЕНИЮ ТЕХНИЧЕСКИХ СРЕДСТВ К СРЕДСТВАМ ИЗМЕРЕНИЙ,Header 2. пункт 3.,Header 3. Исчерпывающий перечень оснований для приостановления или отказа в предоставлении государственной услуги,Header 4. пункт 19.""",, """19. Основания для отказа в предоставлении государственной услуги не предусмотрены законодательством Российской Федерации.
Если техническое средство не предназначено для выполнения количественной оценки величины в допущенных к применению на территории Российской Федерации единицах измерений и/или для него не могут быть установлены показатели точности измерений, то может быть принято решение об отсутствии оснований для отнесения данного технического средства к средствам измерений.""",
Отрывок документа №3
====================="""Header 1. ПРАВИТЕЛЬСТВО РОССИЙСКОЙ ФЕДЕРАЦИИ ПОСТАНОВЛЕНИЕ от 29 июня 2021 г. N 1053 ОБ УТВЕРЖДЕНИИ ПОЛОЖЕНИЯ О ФЕДЕРАЛЬНОМ ГОСУДАРСТВЕННОМ МЕТРОЛОГИЧЕСКОМ КОНТРОЛЕ (НАДЗОРЕ) И О ПРИЗНАНИИ УТРАТИВШИМИ СИЛУ НЕКОТОРЫХ АКТОВ ПРАВИТЕЛЬСТВА РОССИЙСКОЙ ФЕДЕРАЦИИ,Header 2. II. Предмет и объекты надзора,Header 3. пункт 8.""",, """соблюдение обязательных требований к эталонам единиц величин, устанавливаемых в соответствии с частью 8 статьи 7 Федерального закона "Об обеспечении единства измерений".""",

Ответ YaGPT:
 =================
 Согласно постановлению Правительства Российской Федерации от 29 июня 2021 г. № 1053, федеральный государственный метрологический контроль (надзор) включает в себя соблюдение обязательных требований к эталонам единиц величин, устанавливаемых в соответствии с частью 8 статьи 7 Федерального закона «Об обеспечении единства измерений».

В соответствии с приказом Министерства промышленности и торговли Российской Федерации от 25 июня 2013 г. №971, отказ в предоставлении государственной услуги по отнесению технических средств к средствам измерений не предусмотрен законодательством Российской Федерации.

Таким образом, действия ЦСМ по отказу в поверке газового счётчика без действующего договора на техническое обслуживание внутридомового газового оборудования со специализированной организацией не являются правомерными.

Однако для точного ответа на вопрос клиента необходимо знать конкретные обстоятельства и причины отказа ЦСМ в поверке. Возможно, есть другие основания для отказа, которые не указаны в представленных документах.

In [ ]:
#Вопрос пользователя
query_text = 'Что ты умеешь?'
gpt_answer = get_gpt_ya_response(ID_FOLDER, chunks_metadata_question(query_text))
print ("Ответ YaGPT:\n", "=================\n", gpt_answer)

0.19896301747632406
0.217582230591712
0.22344145300153562

Отрывок документа №1
====================="""Header 1. ПРАВИТЕЛЬСТВО РОССИЙСКОЙ ФЕДЕРАЦИИ ПОСТАНОВЛЕНИЕ от 17 июня 2004 г. N 294 О ФЕДЕРАЛЬНОМ АГЕНТСТВЕ ПО ТЕХНИЧЕСКОМУ РЕГУЛИРОВАНИЮ И МЕТРОЛОГИИ,Header 2. II. Полномочия,Header 3. пункт 5.""",, """(пп. 5.11(2) введен Постановлением Правительства РФ от 13.05.2016 N 409)
5.11(3). организует подготовку кадров и дополнительное профессиональное образование в сфере стандартизации;
(пп. 5.11(3) введен Постановлением Правительства РФ от 13.05.2016 N 409)
5.11(4). обеспечивает научную и методическую поддержку проведения работ по стандартизации;
(пп. 5.11(4) введен Постановлением Правительства РФ от 13.05.2016 N 409)
5.11(5). определяет порядок регистрации стандартов организаций, в том числе технических условий, в Федеральном информационном фонде стандартов;
(пп. 5.11(5) введен Постановлением Правительства РФ от 31.05.2021 N 834)
5.11(6). определяет порядок разработки и утверждения технических спецификаций (отчетов);
(пп. 5.11(6) введен Постановлением Правительства РФ от 31.05.2021 N 834)
5.11(7). осуществляет создание, модернизацию и обеспечение эксплуатации информационной системы в сфере стандартизации;
(пп. 5.11(7) введен Постановлением Правительства РФ от 31.05.2021 N 834)
5.12. осуществляет в соответствии с законодательством Российской Федерации работу по комплектованию, хранению, учету и использованию архивных документов, образовавшихся в процессе деятельности Агентства;
5.13. осуществляет функции главного распорядителя и получателя средств федерального бюджета, предусмотренных на содержание Агентства и реализацию возложенных на Агентство функций;
5.14. организует в установленном порядке конгрессы, конференции, семинары, выставки и другие мероприятия в сфере деятельности Агентства;
5.15. осуществляет иные функции по управлению государственным имуществом и оказанию государственных услуг в установленной сфере деятельности, если такие функции предусмотрены федеральными законами, нормативными правовыми актами Президента Российской Федерации и Правительства Российской Федерации.""",
Отрывок документа №2
====================="""Header 1. ПРАВИТЕЛЬСТВО РОССИЙСКОЙ ФЕДЕРАЦИИ ПОСТАНОВЛЕНИЕ от 31 октября 2009 г. N 879 ОБ УТВЕРЖДЕНИИ ПОЛОЖЕНИЯ О ЕДИНИЦАХ ВЕЛИЧИН, ДОПУСКАЕМЫХ К ПРИМЕНЕНИЮ В РОССИЙСКОЙ ФЕДЕРАЦИИ,Header 2. ПРОИЗВОДНЫЕ ЕДИНИЦЫ МЕЖДУНАРОДНОЙ СИСТЕМЫ ЕДИНИЦ (СИ)""",, """───────────────────────────┬─────────────────────────────────────────────────────────────────────
Наименование величины   │                          Единица величины
├──────────────────┬────────────────────────┬─────────────────────────
│   наименование   │      обозначение       │выражение через основные
│                  ├──────────────┬─────────┤и производные единицы СИ
│                  │международное │ русское │
───────────────────────────┴──────────────────┴──────────────┴─────────┴─────────────────────────
-1
1. Плоский угол            радиан                  rad          рад           м·м   = 1
2  -2
2. Телесный угол           стерадиан                sr          ср            м ·м   = 1
2           2                 2
3. Площадь                 квадратный метр          m           м                 м
3           3                 3
4. Объем                   кубический метр          m           м                 м
-1
5. Скорость                метр в секунду          m/s          м/с             м·с
2           2                -2
6. Ускорение               метр на секунду         m/s         м/с              м·с
в квадрате
-1
7. Частота                 герц                     Hz          Гц               с
-2
8. Сила                    ньютон                   N            Н             м·кг·с
3            3                -3
9. Плотность               килограмм на           kg/m         кг/м             кг·м
кубический метр
-1    -2
10. Давление               паскаль                  Ра          Па            м  ·кг·с
2     -2
11. Энергия, работа,       джоуль                   J           Дж            м ·кг·с
количество теплоты
2     -2  -1
12. Теплоемкость           джоуль на кельвин       J/K         Дж/К         м ·кг·с  ·K
2     -3
13. Мощность               ватт                     W           Вт            м ·кг·с
14. Электрический заряд,   кулон                    C           Кл               с·А
количество электричества
2     -3  -1
15. Электрическое          вольт                    V            В          м ·кг·с  ·А
напряжение, электрический
потенциал, разность
электрических потенциалов,
электродвижущая сила
-2   -1  4  2
16. Электрическая емкость  фарад                    F            Ф          м  ·кг  ·с ·А
2     -3  -2
17. Электрическое          ом                       Омега       Ом          м ·кг·с  ·А
сопротивление
-2   -1  3  2
18. Электрическая          сименс                   S           См          м  ·кг  ·с ·А
проводимость
2     -2  -1
19. Поток магнитной        вебер                    Wb          Вб          м ·кг·с  ·А
индукции, магнитный поток
-2  -1
20. Плотность магнитного   тесла                    T           Тл            кг·с  ·А
потока, магнитная индукция
2     -2  -2""",
Отрывок документа №3
====================="""Header 1. ПРАВИТЕЛЬСТВО РОССИЙСКОЙ ФЕДЕРАЦИИ ПОСТАНОВЛЕНИЕ от 31 октября 2009 г. N 879 ОБ УТВЕРЖДЕНИИ ПОЛОЖЕНИЯ О ЕДИНИЦАХ ВЕЛИЧИН, ДОПУСКАЕМЫХ К ПРИМЕНЕНИЮ В РОССИЙСКОЙ ФЕДЕРАЦИИ,Header 2. ВНЕСИСТЕМНЫЕ ЕДИНИЦЫ ВЕЛИЧИН""",, """килограмм-сила     kgf/cm        кгс/см        98066,5 Па           все области
на
квадратный
сантиметр
миллиметр        mm H O      мм вод.ст.      9,80665 Па           все области
водяного столба         2
метр водяного      m H O        м вод.ст.      9806,65 Па           все области
столба            2
4
атмосфера           -            ат        9,80665·10 Па          все области
техническая
миллиметр         mm Hg       мм рт.ст.     133,3224 Па            медицина,
ртутного столба                                                     метеорология,
авиационная навигация
(в ред. Постановления Правительства РФ от 15.08.2015 N 847)
-1
9. Оптическая сила      диоптрия           -           дптр           1·м                  оптика
-6
10. Линейная              текс            tex          текс        1·10   кг/м           текстильная
плотность                                                                              промышленность
11. Скорость              узел            kn            уз          0,514 м/с         морская навигация
(приблизительно)
2
12. Ускорение             гал             Gal          Гал          0,01 м/с             гравиметрия
-1
13. Частота             оборот в          r/s          об/с           1 с              электротехника,
вращения                секунду                                                        промышленность
-1
оборот в минуту      r/min        об/мин     1/60 с   = 0,016
-1
с
(приблизительно)
-19
14. Энергия          электрон-вольт       eV            эВ       1,60218·10    Дж          физика
(приблизительно)
6
киловатт-час       kW·h         кВт·ч         3,6·10  Дж         электротехника
15. Полная            вольт-ампер         V·A          В·А              -              электротехника
мощность
16. Реактивная            вар             var          вар              -              электротехника
мощность
3
17. Электрический      ампер-час          A·h          А·ч          3,6·10  Кл         электротехника
заряд, количество
электричества
18. Количество            бит             bit          бит              -              информационные
информации                                                                            технологии, связь
байт         B (byte)        байт             -
19. Скорость         бит в секунду       bit/s        бит/с             -              информационные
передачи информации                                                                   технологии, связь
байт в секунду  B/s (byte/s)     байт/с            -
-4
20. Экспозиционная      рентген            R            Р       2,57976·10   Кл/кг     ядерная физика,
доза фотонного                                                   (приблизительно)         медицина
излучения
(экспозиционная
доза гамма-
излучения и
рентгеновского
излучения)""",

Ответ YaGPT:
 =================
 Как юридический консультант по метрологическому обеспечению, я могу помочь клиентам с вопросами, касающимися законодательства и нормативных документов в области метрологии.

В рамках своей компетенции я могу предоставить информацию о правовых основах метрологической деятельности, о требованиях к средствам измерений, о порядке проведения поверок и калибровок, а также о других аспектах метрологического обеспечения.

Я не могу дать ответ на вопрос «Что ты умеешь?», так как он не относится к моей компетенции. Однако я могу порекомендовать обратиться к специалистам в области метрологического обеспечения для получения более подробной информации.

In [ ]:
#Вопрос пользователя
query_text = 'Привет!'
gpt_answer = get_gpt_ya_response(ID_FOLDER, chunks_metadata_question(query_text))
print ("Ответ YaGPT:\n", "=================\n", gpt_answer)

0.27152318136487574
0.29894436989114936
0.2731239574642409

Отрывок документа №1
====================="""Header 1. ПРАВИЛА ПО МЕЖГОСУДАРСТВЕННОЙ СТАНДАРТИЗАЦИИ ПОРЯДОК ПРИЗНАНИЯ РЕЗУЛЬТАТОВ ИСПЫТАНИЙ И УТВЕРЖДЕНИЯ ТИПА, ПЕРВИЧНОЙ ПОВЕРКИ, МЕТРОЛОГИЧЕСКОЙ АТТЕСТАЦИИ СРЕДСТВ ИЗМЕРЕНИЙ Procedure for recognition of test results and type approval, initial verification, metrological certification of measuring instruments ПМГ 06-2019,Header 2. 2 Основные положения,Header 3. пункт 2.""",, """Национальный орган в срок, не превышающий 30 календарных дней с даты получения заявки от национального органа государства - участника Соглашения, на территории которого заявитель осуществляет выпуск из производства СИ утвержденного типа, принимает решение о внесении изменений в методику поверки, и (или) изменении интервала между поверками, и (или) внесении изменений в сведения о поверочной лаборатории, проводящей первичную поверку, размещает сведения в информационном фонде в области обеспечения единства измерений и направляет соответствующее уведомление в национальный орган государства - участника Соглашения, на территории которого заявитель осуществляет выпуск из производства СИ утвержденного типа, и заявителю.
Взимание платы, связанной с процедурой внесения изменений в методику поверки, и (или) изменения интервала между поверками, и (или) изменения сведений о поверочной лаборатории, проводящей первичную поверку, не предусмотрено.
2.12 В случае изменения наименования изготовителя или его формы собственности заявитель направляет в национальный орган, признавший утверждение типа и первичную поверку изготавливаемого им СИ, копию свидетельства (сертификата) об утверждении типа СИ с приложением описания типа СИ (для национального реестра СИ), выданного национальным органом государства - участника Соглашения, на территории которого заявитель осуществляет выпуск из производства СИ утвержденного типа. Форма заявки приведена в приложении Ж.
Национальный орган в срок, не превышающий 30 календарных дней с даты получения заявки, принимает решение о внесении изменений в ранее принятое решение о признании утверждения типа и первичной поверки СИ, размещает сведения в информационном фонде в области обеспечения единства измерений и направляет соответствующее уведомление заявителю.
Взимание платы, связанной с процедурой изменения наименования изготовителя или его формы собственности, не предусмотрено.
2.13 По окончании срока действия свидетельства (сертификата) об утверждении типа СИ признание утверждения типа и первичной поверки СИ может быть продлено национальным органом на последующий срок действия свидетельства (сертификата) об утверждении типа СИ.""",
Отрывок документа №2
====================="""Header 1. МИНИСТЕРСТВО ПРОМЫШЛЕННОСТИ И ТОРГОВЛИ РОССИЙСКОЙ ФЕДЕРАЦИИ ФЕДЕРАЛЬНОЕ АГЕНТСТВО ПО ТЕХНИЧЕСКОМУ РЕГУЛИРОВАНИЮ И МЕТРОЛОГИИ ПРИКАЗ от 20 сентября 2019 г. N 2173 ОБ УТВЕРЖДЕНИИ АДМИНИСТРАТИВНОГО РЕГЛАМЕНТА ПРЕДОСТАВЛЕНИЯ ФЕДЕРАЛЬНЫМ АГЕНТСТВОМ ПО ТЕХНИЧЕСКОМУ РЕГУЛИРОВАНИЮ И МЕТРОЛОГИИ ГОСУДАРСТВЕННОЙ УСЛУГИ ПО ПРЕДОСТАВЛЕНИЮ ДОКУМЕНТОВ И СВЕДЕНИЙ, СОДЕРЖАЩИХСЯ В ФЕДЕРАЛЬНОМ ИНФОРМАЦИОННОМ ФОНДЕ ПО ОБЕСПЕЧЕНИЮ ЕДИНСТВА ИЗМЕРЕНИЙ,Header 2. пункт 2.,Header 3. Перечень нормативных правовых актов, регулирующих порядок досудебного (внесудебного) обжалования решений и действий (бездействия) органа, предоставляющего государственную услугу, а также его должностных лиц,Header 4. пункт 73.""",, """уведомление о переадресации обращения
______________________   _______________   ________________________________
должность <*>            подпись             расшифровка подписи
--------------------------------
<*> В случае, если Заявителем является физическое лицо, данные поля не заполняются.
Документ предоставлен КонсультантПлюс
Зарегистрировано в Минюсте России 8 февраля 2019 г. N 53732""",
Отрывок документа №3
====================="""""",, """Документ предоставлен КонсультантПлюс""",

Ответ YaGPT:
 =================
 В представленных документах содержится информация о порядке признания результатов испытаний и утверждения типа, первичной поверки и метрологической аттестации средств измерений.

В частности, в них говорится о том, что национальный орган в срок, не превышающий 30 календарных дней с даты получения заявки, принимает решение о внесении изменений в методику поверки, изменении интервала между поверками или сведений о поверочной лаборатории, проводящей первичную поверку. Также национальный орган принимает решение об изменении наименования изготовителя или его формы собственности.

Кроме того, документы содержат информацию о том, как осуществляется процедура продления срока действия свидетельства (сертификата) об утверждении типа средств измерений.

Также в документах указано, что взимание платы, связанной с процедурой внесения изменений, не предусмотрено.

Таким образом, национальный орган осуществляет признание результатов испытаний, утверждение типа, первичную поверку и метрологическую аттестацию средств измерений в соответствии с установленными процедурами.

In [ ]:
#Вопрос пользователя
query_text = 'Почему идет дождь?'
gpt_answer = get_gpt_ya_response(ID_FOLDER, chunks_metadata_question(query_text))
print ("Ответ YaGPT:\n", "=================\n", gpt_answer)

0.18365930097595928
0.18424464957118913
0.18818066341695217

Отрывок документа №1
====================="""Header 1. РОССИЙСКАЯ ФЕДЕРАЦИЯ ФЕДЕРАЛЬНЫЙ ЗАКОН ОБ ОБЕСПЕЧЕНИИ ЕДИНСТВА ИЗМЕРЕНИЙ,Header 2. Статья 16. Утратила силу с 1 августа 2011 года. - Федеральный закон от 18.07.2011 N 242-ФЗ. Статья 17. Права и обязанности должностных лиц при осуществлении федерального государственного метрологического контроля (надзора)""",, """(в ред. Федеральных законов от 18.07.2011 N 242-ФЗ, от 11.06.2021 N 170-ФЗ)""",
Отрывок документа №2
====================="""Header 1. ПОРЯДОК АТТЕСТАЦИИ ПЕРВИЧНЫХ РЕФЕРЕНТНЫХ МЕТОДИК (МЕТОДОВ) ИЗМЕРЕНИЙ, РЕФЕРЕНТНЫХ МЕТОДИК (МЕТОДОВ) ИЗМЕРЕНИЙ И МЕТОДИК (МЕТОДОВ) ИЗМЕРЕНИЙ И ИХ ПРИМЕНЕНИЯ""",, """I. Общие положения""",
Отрывок документа №3
====================="""Header 1. ПРАВИТЕЛЬСТВО РОССИЙСКОЙ ФЕДЕРАЦИИ ПОСТАНОВЛЕНИЕ от 31 октября 2009 г. N 879 ОБ УТВЕРЖДЕНИИ ПОЛОЖЕНИЯ О ЕДИНИЦАХ ВЕЛИЧИН, ДОПУСКАЕМЫХ К ПРИМЕНЕНИЮ В РОССИЙСКОЙ ФЕДЕРАЦИИ,Header 2. ВНЕСИСТЕМНЫЕ ЕДИНИЦЫ ВЕЛИЧИН""",, """килограмм-сила     kgf/cm        кгс/см        98066,5 Па           все области
на
квадратный
сантиметр
миллиметр        mm H O      мм вод.ст.      9,80665 Па           все области
водяного столба         2
метр водяного      m H O        м вод.ст.      9806,65 Па           все области
столба            2
4
атмосфера           -            ат        9,80665·10 Па          все области
техническая
миллиметр         mm Hg       мм рт.ст.     133,3224 Па            медицина,
ртутного столба                                                     метеорология,
авиационная навигация
(в ред. Постановления Правительства РФ от 15.08.2015 N 847)
-1
9. Оптическая сила      диоптрия           -           дптр           1·м                  оптика
-6
10. Линейная              текс            tex          текс        1·10   кг/м           текстильная
плотность                                                                              промышленность
11. Скорость              узел            kn            уз          0,514 м/с         морская навигация
(приблизительно)
2
12. Ускорение             гал             Gal          Гал          0,01 м/с             гравиметрия
-1
13. Частота             оборот в          r/s          об/с           1 с              электротехника,
вращения                секунду                                                        промышленность
-1
оборот в минуту      r/min        об/мин     1/60 с   = 0,016
-1
с
(приблизительно)
-19
14. Энергия          электрон-вольт       eV            эВ       1,60218·10    Дж          физика
(приблизительно)
6
киловатт-час       kW·h         кВт·ч         3,6·10  Дж         электротехника
15. Полная            вольт-ампер         V·A          В·А              -              электротехника
мощность
16. Реактивная            вар             var          вар              -              электротехника
мощность
3
17. Электрический      ампер-час          A·h          А·ч          3,6·10  Кл         электротехника
заряд, количество
электричества
18. Количество            бит             bit          бит              -              информационные
информации                                                                            технологии, связь
байт         B (byte)        байт             -
19. Скорость         бит в секунду       bit/s        бит/с             -              информационные
передачи информации                                                                   технологии, связь
байт в секунду  B/s (byte/s)     байт/с            -
-4
20. Экспозиционная      рентген            R            Р       2,57976·10   Кл/кг     ядерная физика,
доза фотонного                                                   (приблизительно)         медицина
излучения
(экспозиционная
доза гамма-
излучения и
рентгеновского
излучения)""",

Ответ YaGPT:
 =================
 Я не могу ответить на вопрос клиента, так как я не обладаю достаточными знаниями в области метеорологии. Однако, я могу порекомендовать обратиться к специалистам в этой области.

Но я могу помочь клиенту найти информацию о метрологическом обеспечении, если у него возникнут вопросы по этой теме.

In [ ]:
import pandas as pd

# Загрузка перечня вопросов-ответов из файла Excel в DataFrame
df = pd.read_excel('output.xlsx')
df.head()

,№ п/п,Вопрос,Идеальный ответ,Ответ GPT
0,1,Какие предъявляются требования к измерениям пр...,Законодательство Российской Федерации об обесп...,NaN
1,2,Какой нормативный правовой акт устанавливает п...,В соответствии с частью 1 статьи 9 Федеральног...,NaN
2,3,Допустимо ли проведение процедуры калибровки с...,Сфера государственного регулирования обеспечен...,NaN
3,4,Возможно ли использование средств измерений в ...,В связи с отсутствием в Вашем обращении информ...,NaN
4,5,"Нужно ли поверять все средства измерений, прим...","Управление метрологии, государственного контро...",NaN

In [ ]:
# Извлечение данных из столбца 'Вопрос' по очереди и запись ответа GPT в столбец Ответ YaGPT_chunks

for question in df['Вопрос']:
    df['Ответ YaGPT_chunks'] = df['Вопрос'].apply(lambda x: get_gpt_ya_response(ID_FOLDER, x))

In [ ]:
df

,№ п/п,Вопрос,Идеальный ответ,Ответ GPT,Ответ YaGPT_chunks
0,1,Какие предъявляются требования к измерениям пр...,Законодательство Российской Федерации об обесп...,NaN,В соответствии с Федеральным законом от 26.06....
1,2,Какой нормативный правовой акт устанавливает п...,В соответствии с частью 1 статьи 9 Федеральног...,NaN,В соответствии с Федеральным законом от 26.06....
2,3,Допустимо ли проведение процедуры калибровки с...,Сфера государственного регулирования обеспечен...,NaN,В соответствии с Федеральным законом «Об обесп...
3,4,Возможно ли использование средств измерений в ...,В связи с отсутствием в Вашем обращении информ...,NaN,В соответствии с Федеральным законом № 102-ФЗ ...
4,5,"Нужно ли поверять все средства измерений, прим...","Управление метрологии, государственного контро...",NaN,"**Нужно ли поверять все средства измерений, пр..."
5,6,"Как определить, относятся ли измерения, провод...",В соответствии со статьей 9 Федерального закон...,NaN,В соответствии с Федеральным законом № 102-ФЗ ...
6,7,Можно ли применять средство измерений неутверж...,Для применения средства измерений неутвержден...,NaN,В соответствии с Федеральным законом № 102-ФЗ ...
7,8,Просим рассмотреть предложения по доработке пр...,В соответствии с частью 4 статьи 13 Федерально...,NaN,В соответствии с Федеральным законом «Об обесп...
8,9,"Каковы особенности поверки средств измерений, ...",Согласно пункту 13 Порядка проведения поверки ...,NaN,"Особенности поверки средств измерений, поступи..."
9,10,Можете ли Вы предоставить выписку из Федеральн...,Предоставление из Федерального информационного...,NaN,Для получения выписки из Федерального информац...
10,11,Какие документы относятся к документам по стан...,В соответствии со статьей 14 Федерального зако...,NaN,К документам по стандартизации относятся докум...
11,12,ЦСМ отказал в поверке газового счетчика по при...,Законодательство Российской Федерации об обесп...,NaN,Для ответа на вопрос о правомерности действий ...
12,13,Поверители не выдают свидетельство о поверке (...,В Федеральном информационном фонде по обеспече...,NaN,Для ответа на этот вопрос необходимо знать кон...
13,14,Прошу исключить из базы данных Федерального ин...,В соответствии с пунктом 27 Порядка проведени...,NaN,Для исключения сведений о проведённой поверке ...
14,15,Возможно ли применение средств измерений после...,В соответствии с частью 1 статьи 9 Федеральног...,NaN,В соответствии с Федеральным законом № 102-ФЗ ...
15,16,Прошу дать разъяснения в части применения стат...,В соответствии с частью 1 статьи 5 Федеральног...,NaN,Статья 5 Федерального закона от 26.06.2008 № 1...
16,17,Прошу дать разъяснения по вопросу применения м...,В соответствии с законодательством Российской ...,NaN,Для ответа на этот вопрос необходимо обратитьс...
17,18,Наша организация хотела бы внести в реестр сре...,В соответствии с частью 2 статьи 12 Федерально...,NaN,Для внесения в реестр средств измерений издели...
18,19,Какой документ (документы) устанавливает метро...,Установленные при проведении испытаний и утвер...,NaN,В соответствии с Федеральным законом от 26.06....
19,20,Как или каким документом (документами) руковод...,При отсутствии в Фонде сведений о методиках по...,NaN,В соответствии с Федеральным законом от 26.06....
20,21,Можно ли приобрести для лицензирования техниче...,Вопросы закупки средств измерений в соответств...,NaN,В соответствии с Федеральным законом № 102-ФЗ ...
21,22,Группа компаний IEK (далее ГК IEK) является од...,Законодательство Российской Федерации об обесп...,NaN,Для ответа на этот вопрос необходимо знать сод...
22,23,Прошу предоставить информацию о порядке примен...,В соответствии с частью 1 статьи 12 Федерально...,NaN,В соответствии с Федеральным законом № 102-ФЗ ...
23,24,В 2018 г. мне в ГСК установили электрический с...,В Федеральном информационном фонде по обеспече...,NaN,Для решения данной ситуации необходимо выполни...
24,25,"Согласно ФЗ № 102 ""Об обеспечении единства сре...",Сведения об утвержденных типах средств измерен...,NaN,Согласно пункту 4 приказа Минпромторга России ...
25,26,Прошу сообщить проходил ли поверку измерительн...,"Информируем, что норма о подтверждении результ...",NaN,Для ответа на этот вопрос необходимо знать тип...
26,27,"В соответствии с Федеральным законом ""О порядк...",В соответствии с частью 5.1 статьи 11 Федераль...,NaN,В соответствии с Федеральным законом «О порядк...
27,28,Нужно внести в реестр Минпромторга металлическ...,Для включения сведений об утвержденном типе ср...,NaN,Для внесения в реестр Минпромторга металлическ...
28,29,обязан ли поставщик или производитель вносить ...,В соответствии с частью 3 статьи 12 Федерально...,NaN,**Обязан ли поставщик или производитель вносит...
29,30,В настоящий момент в нашей организации находят...,"Места установки пломб, ограничивающих доступ к...",NaN,В соответствии с Федеральным законом № 102-ФЗ ...
30,31,Прошу Вас рассмотреть вопрос о несоответствии ...,Пунктом 3 Порядка установления и изменения инт...,NaN,Для ответа на этот вопрос необходимо знать кон...
31,32,В связи с введением иностранными компаниями то...,Вопросы подбора аналогов средств измерений тре...,NaN,Для того чтобы предоставить вам информацию об ...
32,33,"Прошу разъяснить, какая организация уполномоче...",Установление методик поверки осуществляется пр...,NaN,В соответствии с пунктом 11 Порядка копировани...
33,34,Подлежат ли регулярной актуализации (юридическ...,Регулярная актуализация методик поверки аккред...,NaN,В соответствии с Федеральным законом от 26.06....
34,35,"Прошу Вас дать разъяснение о том, кто может оф...",Вопросы оформления паспортов средств измерений...,NaN,В соответствии с Федеральным законом № 102-ФЗ ...
35,36,Прошу разъяснить: если на сайте https://fgis.g...,"Методики (методы) измерений, сведения о которы...",NaN,Если статус методики установлен как «действует...
36,37,Необходимо ли проводить внеочередную поверку п...,Законодательство Российской Федерации об обесп...,NaN,В соответствии с Федеральным законом № 102-ФЗ ...
37,38,В мае купили прибор учета воды с отметкой о за...,В соответствии с частью 4 статьи 13 Федерально...,NaN,Сведения о поверке приборов учёта воды вносятс...
38,39,В 2022 году нам в лабораторию поставили новые ...,В соответствии с частью 2 статьи 1 Федеральног...,NaN,В соответствии с частью 2 статьи 9 Федеральног...
39,40,Возможно ли заполнение записи (свидетельства) ...,В соответствии с частью 6 статьи 13 Федерально...,NaN,В соответствии с Федеральным законом № 102-ФЗ ...
40,41,Прошу сообщить сведения результатах поверки.,Сведения о результате поверки средства измерен...,NaN,Сведения о результатах поверки содержатся в св...
41,42,Является ли средством измерений утвержденного ...,"Статус «действует», указанный в поле «Дополнит...",NaN,"Да, средство измерений, в сведениях об утвержд..."
42,43,Наша организация является правообладателем утв...,Законодательством Российской Федерации об обес...,NaN,В соответствии с Федеральным законом № 102-ФЗ ...
43,44,Возможно ли использование в качестве эталона в...,Для применения средства измерений неутвержденн...,NaN,В соответствии с Федеральным законом от 26.06....

In [ ]:
#Сохраним ответы обученной LLM в файл
df.to_excel('answer_YaGPT_bd_03_chunks+metadata.xlsx', index=False)